#
# Makefile for the Linux Kernel IPS specific device drivers.
#
obj-$(CONFIG_X2_IPS) += x2_ips.o
obj-$(CONFIG_X2_IPS) += x2_ips_cdev.o
obj-y += mipi/
obj-$(CONFIG_X2_SIF) += sif/
obj-$(CONFIG_USRDRV) += usrdrv/
obj-$(CONFIG_HZ_DSI) += dsihost_interface_axi/
obj-$(CONFIG_KERNEL_CLIENT) += client_in_kernel/
obj-$(CONFIG_X2_IPU) += ipu/
obj-$(CONFIG_X2_ISP) += isp/